name: Build and Publish Release

on:
  release:
    types: [published]

jobs:
  build-and-push-mautrix-wechat:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get Tag Name
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=tag_name;]$(echo ${GITHUB_REF#refs/heads/}-$(date +'%Y%m%d')$(git rev-parse --short HEAD))"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Build and Publish mautrix-wechat ${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
        id: docker_build_mautrix_tagged_version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: leishi1313/mautrix-wechat:${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
      - if: github.event_name == 'release'
        name: Build and Publish Latest
        id: docker_build_mautrix_wechat_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: leishi1313/mautrix-wechat:latest
      - name: mautrix-wechat digest
        run: echo ${{ steps.docker_build_frontend_tagged_version.outputs.digest }}

  build-and-push-mautrix-wechat-box:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get Tag Name
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=tag_name;]$(echo ${GITHUB_REF#refs/heads/}-$(date +'%Y%m%d')$(git rev-parse --short HEAD))"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Build and Publish mautrix-wechat-box ${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
        id: docker_build_mautrix_box_tagged_version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-box
          push: true
          add-hosts:
            - "dldir1.qq.com:127.0.0.1"
          tags: leishi1313/mautrix-wechat-box:${{ github.event.release.tag_name || steps.vars.outputs.tag_name }}
      - if: github.event_name == 'release'
        name: Build and Publish Latest
        id: docker_build_mautrix_wechat_box_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-box
          push: true
          add-hosts:
            - "dldir1.qq.com:127.0.0.1"
          tags: leishi1313/mautrix-wechat-box:latest
      - name: mautrix-wechat-box digest
        run: echo ${{ steps.docker_build_frontend_tagged_version.outputs.digest }}

  build-and-publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pdm install
          twine upload dist/*
